### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by brianteeman** [joomla-framework/di#33]
https://github.com/joomla-framework/di/blob/dfe260ca94e720b666993a8924528bb87213976c/src/Container.php#L503

I was reviewing the deprecated messages in my Joomla 4 install and was confused by this one

`2018-09-14T11:30:12+00:00	WARNING 127.0.0.1	deprecated	Joomla\DI\Container::exists() is deprecated and will be removed in 3.0, use Psr\Container\ContainerInterface::has() instead.`

So I came here to suggest that the message was clarified to include framework or similar so it was clearer when you hit the message in the CMS.

But then I discovered that the message doesn't exist here and the version of this file in my j4 install is completely different to this one??

**Comment by mbabker** [comment]
We only have the `trigger_error()` calls on the 2.0 branches across the Framework repos, and that's where the message you're seeing comes from.

Also, what exactly is your proposal for "clarified to include framework or similar"?  Unless we're going to start putting product identifiers in all `@since` and `@deprecated` tags as well as the inline deprecation messages (for all products, not just the Framework packages, since everything is on a different version trajectory at this point) I'm not quite sure how you'd best clarify this without creating more confusion (just look at https://api.joomla.org/cms-3/namespaces/Joomla.html where there is a mix of CMS and Framework classes with CMS, Platform, and Framework versioning in place).

**Comment by brianteeman** [comment]
Called by too works for me

**Comment by mbabker** [comment]
Since this was opened, Symfony has a new [deprecation contracts](https://github.com/symfony/deprecation-contracts) package that offers a function that gives runtime errors closer to the format you're looking for.

So with that package [this block](https://github.com/joomla-framework/di/blob/ad4fb4cacbda3581137d862a292a2932dba756ad/src/Container.php#L137-L144) changes to:

```php
trigger_deprecation(
    'joomla/di',
    '1.5.0',
    '%1$s() is deprecated and will be removed in 3.0, use %2$s::has() instead.',
    __METHOD__,
    ContainerInterface::class
);
```

And the resulting runtime message (which is what lands in the CMS logger) is something like this:

```sh
Since joomla/di 1.5.0: Joomla\DI\Container::exists() is deprecated and will be removed in 3.0, use Psr\Container\ContainerInterface::has() instead.
```

Using that package and its helper function is a worthwhile change IMO (and I've done it on other open source packages already) since it does give a little more context as to where the deprecation originates from when you have your PHP runtime collecting `E_USER_DEPRECATED` messages.

Doesn't really help with doc blocks though unless you end up rewriting them all to something similar to Symfony's standard but with package identifiers in them, so something like this:

```php
/**
 * @deprecated in joomla/di 1.5 to be removed in 3.0, use `Container::has()` instead
 */
```

But, the con with doing that is it's going to break quite a bit about how the phpDocumentor build transforms those tags into output (inside the various class pages or the deprecation report).
